[package]
name = "audio_visualizer"
version = "0.1.0"
edition = "2024"

[dependencies]
nannou="0.19"
hound="3.5"
rustfft="6"
anyhow="1"
rodio="0.17"
cpal="0.15"
ringbuf="0.3"
clap={ version="4", features=["derive"] }
